# -*- coding: utf-8 -*-
"""Tasks05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13-FzsaBhUeZsmqsbuQG0Of9Po0UBoBkI
"""

!pip install streamlit

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# Load dataset
df = pd.read_csv("Sample - Superstore.csv", encoding='latin1')

# Dashboard title
st.title("Global Superstore Dashboard")

# Sidebar filters
st.sidebar.header("Filters")

region = st.sidebar.selectbox(
    "Select Region",
    df["Region"].unique()
)

category = st.sidebar.selectbox(
    "Select Category",
    df["Category"].unique()
)

# Apply filters
filtered_df = df[
    (df["Region"] == region) &
    (df["Category"] == category)
]

# KPIs
st.subheader("Key Performance Indicators")

total_sales = filtered_df["Sales"].sum()
total_profit = filtered_df["Profit"].sum()
total_orders = filtered_df["Order ID"].nunique()

st.write("Total Sales:", total_sales)
st.write("Total Profit:", total_profit)
st.write("Total Orders:", total_orders)

# Top 5 customers
st.subheader("Top 5 Customers")

top_customers = (
    filtered_df.groupby("Customer Name")["Sales"]
    .sum()
    .sort_values(ascending=False)
    .head(5)
)

st.bar_chart(top_customers)

# Profit by Sub-Category
st.subheader("Profit by Sub-Category")

profit_subcategory = (
    filtered_df.groupby("Sub-Category")["Profit"]
    .sum()
    .sort_values()
)

st.bar_chart(profit_subcategory)

# Sales Trend
st.subheader("Sales Trend")

df["Order Date"] = pd.to_datetime(df["Order Date"])
sales_trend = (
    filtered_df.groupby(df["Order Date"].dt.to_period("M"))["Sales"]
    .sum()
)

sales_trend.index = sales_trend.index.astype(str)

st.line_chart(sales_trend)

# Show filtered data
st.subheader("Filtered Data")
st.dataframe(filtered_df)

"""### 1. Save your Streamlit code to a Python file

First, we need to save the Streamlit application code into a Python file. I'll name it `dashboard_app.py`.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile dashboard_app.py
# 
# import streamlit as st
# import pandas as pd
# import matplotlib.pyplot as plt
# 
# # Load dataset
# df = pd.read_csv("Sample - Superstore.csv", encoding='latin1')
# 
# # Dashboard title
# st.title("Global Superstore Dashboard")
# 
# # Sidebar filters
# st.sidebar.header("Filters")
# 
# region = st.sidebar.selectbox(
#     "Select Region",
#     df["Region"].unique()
# )
# 
# category = st.sidebar.selectbox(
#     "Select Category",
#     df["Category"].unique()
# )
# 
# # Apply filters
# filtered_df = df[
#     (df["Region"] == region) &
#     (df["Category"] == category)
# ]
# 
# # KPIs
# st.subheader("Key Performance Indicators")
# 
# total_sales = filtered_df["Sales"].sum()
# total_profit = filtered_df["Profit"].sum()
# total_orders = filtered_df["Order ID"].nunique()
# 
# st.write("Total Sales:", total_sales)
# st.write("Total Profit:", total_profit)
# st.write("Total Orders:", total_orders)
# 
# # Top 5 customers
# st.subheader("Top 5 Customers")
# 
# top_customers = (
#     filtered_df.groupby("Customer Name")["Sales"]
#     .sum()
#     .sort_values(ascending=False)
#     .head(5)
# )
# 
# st.bar_chart(top_customers)
# 
# # Profit by Sub-Category
# st.subheader("Profit by Sub-Category")
# 
# profit_subcategory = (
#     filtered_df.groupby("Sub-Category")["Profit"]
#     .sum()
#     .sort_values()
# )
# 
# st.bar_chart(profit_subcategory)
# 
# # Sales Trend
# st.subheader("Sales Trend")
# 
# df["Order Date"] = pd.to_datetime(df["Order Date"])
# sales_trend = (
#     filtered_df.groupby(df["Order Date"].dt.to_period("M"))["Sales"]
#     .sum()
# )
# 
# sales_trend.index = sales_trend.index.astype(str)
# 
# st.line_chart(sales_trend)
# 
# # Show filtered data
# st.subheader("Filtered Data")
# st.dataframe(filtered_df)

"""### 2. Install `ngrok`

We need to install `ngrok` to create a secure tunnel to expose the Streamlit app.
"""

!pip install pyngrok

"""### 3. Authenticate `ngrok`

You will need an `ngrok` authentication token. Get yours from [ngrok.com/signup](https://ngrok.com/signup) and add it to Colab secrets as `NGROK_AUTH_TOKEN`.

"""

from pyngrok import ngrok
from google.colab import userdata
import os

# Fetch your ngrok Authtoken from Colab secrets
NGROK_AUTH_TOKEN = userdata.get('NGROK_AUTH_TOKEN')

# Set ngrok authtoken
ngrok.set_auth_token(NGROK_AUTH_TOKEN)

"""### 4. Run the Streamlit app and expose it with `ngrok`

Now, execute the Python file using `streamlit run` and then create a public URL with `ngrok`. This will output a public URL which you can click to access your dashboard.
"""

import subprocess
import threading
import time
from pyngrok import ngrok

def run_streamlit():
    # Command to run Streamlit
    cmd = ['streamlit', 'run', 'dashboard_app.py']
    # Use subprocess.Popen to run Streamlit in the background
    # Redirect stdout and stderr to avoid blocking the cell and for debugging
    process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    # You can optionally read from stdout/stderr here if needed for live logs
    # For simplicity, we'll let it run and connect ngrok after a delay.

# Start Streamlit in a separate thread
streamlit_thread = threading.Thread(target=run_streamlit)
streamlit_thread.start()

# Give Streamlit a moment to start up (increase if connection issues persist)
time.sleep(15)

# Open a ngrok tunnel to Streamlit's default port (8501)
# Ensure the ngrok authtoken is set before this step
public_url = ngrok.connect(8501)
print(f"Streamlit App URL: {public_url}")

!pip install streamlit pyngrok



# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import matplotlib.pyplot as plt
# 
# # Load dataset
# df = pd.read_csv("Sample - Superstore.csv", encoding="latin1")
# 
# # Dashboard title
# st.title("Global Superstore Dashboard")
# 
# # Sidebar filters
# st.sidebar.header("Filters")
# 
# region = st.sidebar.selectbox(
#     "Select Region",
#     df["Region"].unique()
# )
# 
# category = st.sidebar.selectbox(
#     "Select Category",
#     df["Category"].unique()
# )
# 
# # Apply filters
# filtered_df = df[
#     (df["Region"] == region) &
#     (df["Category"] == category)
# ]
# 
# # KPIs
# st.subheader("Key Performance Indicators")
# 
# total_sales = filtered_df["Sales"].sum()
# total_profit = filtered_df["Profit"].sum()
# total_orders = filtered_df["Order ID"].nunique()
# 
# st.write("Total Sales:", total_sales)
# st.write("Total Profit:", total_profit)
# st.write("Total Orders:", total_orders)
# 
# # Top 5 customers
# st.subheader("Top 5 Customers")
# 
# top_customers = (
#     filtered_df.groupby("Customer Name")["Sales"]
#     .sum()
#     .sort_values(ascending=False)
#     .head(5)
# )
# 
# st.bar_chart(top_customers)
# 
# # Profit by Sub-Category
# st.subheader("Profit by Sub-Category")
# 
# profit_subcategory = (
#     filtered_df.groupby("Sub-Category")["Profit"]
#     .sum()
#     .sort_values()
# )
# 
# st.bar_chart(profit_subcategory)
# 
# # Sales Trend
# st.subheader("Sales Trend")
# 
# df["Order Date"] = pd.to_datetime(df["Order Date"])
# sales_trend = (
#     filtered_df.groupby(df["Order Date"].dt.to_period("M"))["Sales"]
#     .sum()
# )
# 
# sales_trend.index = sales_trend.index.astype(str)
# 
# st.line_chart(sales_trend)
# 
# # Show filtered data
# st.subheader("Filtered Data")
# st.dataframe(filtered_df)

!pkill streamlit

!streamlit run app.py &>/content/logs.txt &

!lt --port 8501

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# 
# # Load dataset (encoding fix)
# df = pd.read_csv(
#     "Sample - Superstore.csv",
#     encoding="latin1",
#     engine="python"
# )
# 
# # Title
# st.title("Global Superstore Dashboard")
# 
# # Sidebar Filters
# st.sidebar.header("Filters")
# 
# region = st.sidebar.selectbox(
#     "Select Region",
#     df["Region"].dropna().unique()
# )
# 
# category = st.sidebar.selectbox(
#     "Select Category",
#     df["Category"].dropna().unique()
# )
# 
# # Filter data
# filtered_df = df[
#     (df["Region"] == region) &
#     (df["Category"] == category)
# ]
# 
# # KPI Section
# st.header("Key Performance Indicators")
# 
# total_sales = filtered_df["Sales"].sum()
# total_profit = filtered_df["Profit"].sum()
# total_orders = filtered_df["Order ID"].nunique()
# 
# st.write("### Total Sales:", total_sales)
# st.write("### Total Profit:", total_profit)
# st.write("### Total Orders:", total_orders)
# 
# # Top Customers
# st.header("Top 5 Customers by Sales")
# 
# top_customers = (
#     filtered_df.groupby("Customer Name")["Sales"]
#     .sum()
#     .sort_values(ascending=False)
#     .head(5)
# )
# 
# st.write(top_customers)
# 
# # Profit by Sub-Category
# st.header("Profit by Sub-Category")
# 
# profit_subcategory = (
#     filtered_df.groupby("Sub-Category")["Profit"]
#     .sum()
#     .sort_values(ascending=False)
# )
# 
# st.write(profit_subcategory)
# 
# # Sales by Segment
# st.header("Sales by Segment")
# 
# sales_segment = (
#     filtered_df.groupby("Segment")["Sales"]
#     .sum()
#     .sort_values(ascending=False)
# )
# 
# st.write(sales_segment)
# 
# # Sales by Ship Mode
# st.header("Sales by Ship Mode")
# 
# ship_mode_sales = (
#     filtered_df.groupby("Ship Mode")["Sales"]
#     .sum()
#     .sort_values(ascending=False)
# )
# 
# st.write(ship_mode_sales)
# 
# # Full Filtered Dataset
# st.header("Filtered Dataset")
# 
# st.write(filtered_df)

!pip install streamlit
!npm install -g localtunnel

!streamlit run app.py &>/content/logs.txt &

!lt --port 8501

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# 
# # Load dataset
# df = pd.read_csv(
#     "Sample - Superstore.csv",
#     encoding="latin1",
#     engine="python"
# )
# 
# # Title
# st.title("Global Superstore Dashboard")
# 
# # Filters
# st.sidebar.header("Filters")
# 
# region = st.sidebar.selectbox(
#     "Select Region",
#     df["Region"].dropna().unique()
# )
# 
# category = st.sidebar.selectbox(
#     "Select Category",
#     df["Category"].dropna().unique()
# )
# 
# # Filter data
# filtered_df = df[
#     (df["Region"] == region) &
#     (df["Category"] == category)
# ]
# 
# # KPIs
# st.header("Key Performance Indicators")
# 
# st.text(f"Total Sales: {filtered_df['Sales'].sum()}")
# st.text(f"Total Profit: {filtered_df['Profit'].sum()}")
# st.text(f"Total Orders: {filtered_df['Order ID'].nunique()}")
# 
# # Top 5 Customers
# st.header("Top 5 Customers")
# 
# top_customers = (
#     filtered_df.groupby("Customer Name")["Sales"]
#     .sum()
#     .sort_values(ascending=False)
#     .head(5)
# )
# 
# for customer, sales in top_customers.items():
#     st.text(f"{customer} : {sales}")
# 
# # Profit by Sub-Category
# st.header("Profit by Sub-Category")
# 
# profit_subcategory = (
#     filtered_df.groupby("Sub-Category")["Profit"]
#     .sum()
#     .sort_values(ascending=False)
# )
# 
# for subcat, profit in profit_subcategory.items():
#     st.text(f"{subcat} : {profit}")
# 
# # Sales by Segment
# st.header("Sales by Segment")
# 
# sales_segment = (
#     filtered_df.groupby("Segment")["Sales"]
#     .sum()
#     .sort_values(ascending=False)
# )
# 
# for segment, sales in sales_segment.items():
#     st.text(f"{segment} : {sales}")
# 
# # Sales by Ship Mode
# st.header("Sales by Ship Mode")
# 
# ship_mode_sales = (
#     filtered_df.groupby("Ship Mode")["Sales"]
#     .sum()
#     .sort_values(ascending=False)
# )
# 
# for mode, sales in ship_mode_sales.items():
#     st.text(f"{mode} : {sales}")
# 
# # Show only first 10 rows as plain text
# st.header("Sample Data")
# 
# sample_rows = filtered_df.head(10)
# 
# for i in range(len(sample_rows)):
#     st.text(sample_rows.iloc[i].to_dict())

!pkill streamlit
!streamlit run app.py &>/content/logs.txt &
!lt --port 8501

