# -*- coding: utf-8 -*-
"""Tasks02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16t_87YV-r6iCmbdq1bULVtRa2R7YYorQ
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

# Load dataset
df = pd.read_csv("Mall_Customers.csv")

# Features
X = df[["Annual Income (k$)", "Spending Score (1-100)"]]

# KMeans clustering
kmeans = KMeans(n_clusters=5, random_state=42)
df["Cluster"] = kmeans.fit_predict(X)

# PCA for visualization
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)

# Plot clusters
plt.scatter(X_pca[:,0], X_pca[:,1], c=df["Cluster"])
plt.title("Customer Segmentation using K-Means")
plt.show()

# Cluster summary
print(df.groupby("Cluster").mean(numeric_only=True))

