# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w6sKE8J9O8h_RHIbk3Kf_oklGqs-L5qI
"""

# Install libraries
!pip install prophet xgboost statsmodels

# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from prophet import Prophet
from statsmodels.tsa.arima.model import ARIMA
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error

# Load dataset
df = pd.read_csv("/content/household_power_consumption.txt", sep=';', na_values=['?'])

# Set correct column names
df['Datetime'] = pd.to_datetime(df['Date'] + ' ' + df['Time'], errors='coerce')
datetime_col = "Datetime"
target_col = "Global_active_power"

# Convert datetime
df.dropna(subset=[datetime_col], inplace=True)

# Convert target to numeric
df[target_col] = pd.to_numeric(df[target_col], errors="coerce")

# Fill missing values
df[target_col] = df[target_col].ffill()

# Set index
df.set_index(datetime_col, inplace=True)

# Feature engineering
df["hour"] = df.index.hour
df["day"] = df.index.day
df["month"] = df.index.month
df["weekday"] = df.index.weekday
df["weekend"] = (df["weekday"] >= 5).astype(int)

# -----------------------------
# Prophet Model
# -----------------------------
prophet_df = df.reset_index()[[datetime_col, target_col]]
prophet_df.columns = ["ds", "y"]

train_prophet = prophet_df[:-30]
test_prophet = prophet_df[-30:]

prophet_model = Prophet()
prophet_model.fit(train_prophet)

future = prophet_model.make_future_dataframe(periods=30)
forecast = prophet_model.predict(future)

pred_prophet = forecast["yhat"].tail(30)

mae_prophet = mean_absolute_error(test_prophet["y"], pred_prophet)
rmse_prophet = np.sqrt(mean_squared_error(test_prophet["y"], pred_prophet))

print("Prophet MAE:", mae_prophet)
print("Prophet RMSE:", rmse_prophet)

fig = prophet_model.plot(forecast)
plt.show()

# -----------------------------
# ARIMA Model
# -----------------------------
train_arima = df[target_col][:-30]
test_arima = df[target_col][-30:]

arima_model = ARIMA(train_arima, order=(5,1,0))
arima_fit = arima_model.fit()

pred_arima = arima_fit.forecast(steps=30)

mae_arima = mean_absolute_error(test_arima, pred_arima)
rmse_arima = np.sqrt(mean_squared_error(test_arima, pred_arima))

print("ARIMA MAE:", mae_arima)
print("ARIMA RMSE:", rmse_arima)

# -----------------------------
# XGBoost Model
# -----------------------------
X = df[["hour", "day", "month", "weekday", "weekend"]]
y = df[target_col]

X_train = X[:-30]
X_test = X[-30:]

y_train = y[:-30]
y_test = y[-30:]

xgb_model = XGBRegressor(n_estimators=100)
xgb_model.fit(X_train, y_train)

pred_xgb = xgb_model.predict(X_test)

mae_xgb = mean_absolute_error(y_test, pred_xgb)
rmse_xgb = np.sqrt(mean_squared_error(y_test, pred_xgb))

print("XGBoost MAE:", mae_xgb)
print("XGBoost RMSE:", rmse_xgb)

# -----------------------------
# Final Comparison
# -----------------------------
results = pd.DataFrame({
    "Model": ["Prophet", "ARIMA", "XGBoost"],
    "MAE": [mae_prophet, mae_arima, mae_xgb],
    "RMSE": [rmse_prophet, rmse_arima, rmse_xgb]
})

print("\nFinal Comparison:")
print(results)

# Install libraries
!pip install prophet xgboost statsmodels

# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from prophet import Prophet
from statsmodels.tsa.arima.model import ARIMA
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error

# Load dataset
df = pd.read_csv(
    "household_power_consumption.txt",
    sep=";",
    low_memory=False
)

# Combine Date + Time into Datetime
df["Datetime"] = pd.to_datetime(
    df["Date"] + " " + df["Time"],
    format="%d/%m/%Y %H:%M:%S",
    errors="coerce"
)

# Drop invalid rows and original Date/Time columns
df.dropna(subset=["Datetime"], inplace=True)
df.drop(columns=["Date", "Time"], inplace=True)

# Convert power columns to numeric
for col in [
    "Global_active_power",
    "Global_reactive_power",
    "Voltage",
    "Global_intensity",
    "Sub_metering_1",
    "Sub_metering_2",
    "Sub_metering_3",
]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# Fill missing values after numeric conversion
df.ffill(inplace=True)

# Set index
df.set_index("Datetime", inplace=True)

# Resample hourly
df = df.resample("h").mean()

# Feature engineering
df["hour"] = df.index.hour
df["day"] = df.index.day
df["month"] = df.index.month
df["weekday"] = df.index.weekday
df["weekend"] = (df["weekday"] >= 5).astype(int)

# -----------------------------
# Prophet Model
# -----------------------------
prophet_df = df.reset_index()[["Datetime", "Global_active_power"]]
prophet_df.columns = ["ds", "y"]

train_prophet = prophet_df[:-30]
test_prophet = prophet_df[-30:]

prophet_model = Prophet()
prophet_model.fit(train_prophet)

future = prophet_model.make_future_dataframe(periods=30, freq="h")
forecast = prophet_model.predict(future)

pred_prophet = forecast["yhat"].tail(30)

mae_prophet = mean_absolute_error(test_prophet["y"], pred_prophet)
rmse_prophet = np.sqrt(mean_squared_error(test_prophet["y"], pred_prophet))

print("Prophet MAE:", mae_prophet)
print("Prophet RMSE:", rmse_prophet)

fig = prophet_model.plot(forecast)
plt.show()

# -----------------------------
# ARIMA Model
# -----------------------------
train_arima = df["Global_active_power"][:-30]
test_arima = df["Global_active_power"][-30:]

arima_model = ARIMA(train_arima, order=(5,1,0))
arima_fit = arima_model.fit()

pred_arima = arima_fit.forecast(steps=30)

mae_arima = mean_absolute_error(test_arima, pred_arima)
rmse_arima = np.sqrt(mean_squared_error(test_arima, pred_arima))

print("ARIMA MAE:", mae_arima)
print("ARIMA RMSE:", rmse_arima)

# -----------------------------
# XGBoost Model
# -----------------------------
X = df[["hour", "day", "month", "weekday", "weekend"]]
y = df["Global_active_power"]

X_train = X[:-30]
X_test = X[-30:]

y_train = y[:-30]
y_test = y[-30:]

xgb_model = XGBRegressor(n_estimators=100)
xgb_model.fit(X_train, y_train)

pred_xgb = xgb_model.predict(X_test)

mae_xgb = mean_absolute_error(y_test, pred_xgb)
rmse_xgb = np.sqrt(mean_squared_error(y_test, pred_xgb))

print("XGBoost MAE:", mae_xgb)
print("XGBoost RMSE:", rmse_xgb)

# Final Comparison
results = pd.DataFrame({
    "Model": ["Prophet", "ARIMA", "XGBoost"],
    "MAE": [mae_prophet, mae_arima, mae_xgb],
    "RMSE": [rmse_prophet, rmse_arima, rmse_xgb]
})

print("\nFinal Comparison:")
print(results)

